name: End-to-end tests
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: hangman-e2e/e2e/package-lock.json
      - name: build
        working-directory: .hangman-e2e/e2e
        run: |
          npm ci
          npm run build --if-present
  cypress-run:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          project: ./e2e
          browser: chrome
      - name: build docker containers
        run: |
          docker run -d -p 3001:3000 jaimesalas/hangman-api
          docker run -d -p 8080:8080 -e API_URL=http://localhost:3001 jaimesalas/hangman-front
          npm run open
