name: End-to-end tests
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: build
        working-directory: ./
        run: |
          npm ci
          npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: build-code
          path: cypress/
  e2e-test:
    runs-on: ubuntu-latest
    needs: build
    steps: 
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            name: build-code
            path: cypress/
        - name: Cypress run
          run: |
            docker run -d -p 3001:3000 jaimesalas/hangman-api
            docker run -d -p 8080:8080 -e API_URL=http://localhost:3001 jaimesalas/hangman-front
        - uses: cypress-io/github-action@v5
          with:
            project: .
            browser: chrome
